// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Jacobbrewer1/proxy/pkg/logging"
	"github.com/gorilla/mux"
)

// Injectors from wire.go:

func initializeApp() (*app, error) {
	loggingAppName := _wireAppNameValue
	config := logging.NewConfig(loggingAppName)
	logger, err := logging.CommonLogger(config)
	if err != nil {
		return nil, err
	}
	router := mux.NewRouter()
	mainConfiguration, err := newConfiguration()
	if err != nil {
		return nil, err
	}
	mainApp := newApp(logger, router, mainConfiguration)
	return mainApp, nil
}

var (
	_wireAppNameValue = logging.AppName(appName)
)
