// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jacobbrewer1/reverse-proxy/cmd/udp/config"
	"github.com/jacobbrewer1/reverse-proxy/pkg/logging"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	loggerName := _wireLoggerNameValue
	loggerPath := _wireLoggerPathValue
	loggingConfig := logging.NewConfig(loggerName, loggerPath)
	logger, err := logging.CommonLogger(loggingConfig)
	if err != nil {
		return nil, err
	}
	configConfig, err := config.NewConfig(loggingConfig)
	if err != nil {
		return nil, err
	}
	app := NewApp(logger, configConfig)
	return app, nil
}

var (
	_wireLoggerNameValue = logging.LoggerName(config.AppName)
	_wireLoggerPathValue = logging.LoggerPath(config.LogFilePath)
)
