// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jacobbrewer1/reverse-proxy/pkg/logging"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	loggerName := _wireLoggerNameValue
	loggerPath := _wireLoggerPathValue
	config := logging.NewConfig(loggerName, loggerPath)
	logger, err := logging.CommonLogger(config)
	if err != nil {
		return nil, err
	}
	mainConfig := NewConfig(config)
	server := newHttpServer(logger, mainConfig)
	mainProxyServer := newProxyServer(logger, mainConfig)
	app := newApp(logger, server, mainProxyServer, mainConfig)
	return app, nil
}

var (
	_wireLoggerNameValue = logging.LoggerName(appName)
	_wireLoggerPathValue = logging.LoggerPath(logFilePath)
)
